project_id = "mgpzowiahnwcmcaelogf"

[functions.check-email-exists]
verify_jwt = false

[functions.evolution-whatsapp]
verify_jwt = true

[functions.send-order-whatsapp]
verify_jwt = false

[functions.meta-tags-proxy]
verify_jwt = false

[functions.migrate-product-images]
verify_jwt = true
